# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.cache/wt [current_project]
set_property parent.project_path D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Work/vivado_project/DLC/MiniMIPS32/benchmark/5.sort/board/sort_board_inst.coe
add_files d:/Work/vivado_project/DLC/MiniMIPS32/benchmark/5.sort/board/sort_board_data.coe
read_verilog -library xil_defaultlib -sv {
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/defines.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/MiniMIPS32.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/exe_stage.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/id_stage.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/if_stage.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/mem_stage.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/regfile.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/wb_stage.sv
  D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/MiniMIPS32_SYS.sv
}
read_ip -quiet D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all d:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/Work/vivado_project/DLC/MiniMIPS32/MiniMIPS32.srcs/constrs_1/new/pin.xdc]


synth_design -top MiniMIPS32_SYS -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MiniMIPS32_SYS.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MiniMIPS32_SYS_utilization_synth.rpt -pb MiniMIPS32_SYS_utilization_synth.pb"
